//
// Copyright (c) 2026
//
// SPDX-License-Identifier: Apache-2.0
//

// Migration coordinator — shim-to-shim handoff protocol for Kata
// live migration. See
// docs/design/live-migration-shim-lifecycle.md for the conceptual
// contract and the handoff sequence diagram.
//
// This service is bound by the destination shim on a per-sandbox
// unix socket only when the experimental.live_migration feature is
// enabled. It is NOT exposed to containerd or any other client.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: migration_coordinator.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MigrationCoordinator_PrepareIncoming_FullMethodName  = "/migration_coordinator.MigrationCoordinator/PrepareIncoming"
	MigrationCoordinator_SendSandboxState_FullMethodName = "/migration_coordinator.MigrationCoordinator/SendSandboxState"
	MigrationCoordinator_CompleteHandoff_FullMethodName  = "/migration_coordinator.MigrationCoordinator/CompleteHandoff"
	MigrationCoordinator_AbortHandoff_FullMethodName     = "/migration_coordinator.MigrationCoordinator/AbortHandoff"
)

// MigrationCoordinatorClient is the client API for MigrationCoordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MigrationCoordinatorClient interface {
	// PrepareIncoming is called by the source shim once the
	// destination shim is up and its hypervisor is in -incoming
	// mode. The destination acks readiness with the URI that QEMU
	// is listening on, so the source can target its QMP migrate
	// command at the right address.
	PrepareIncoming(ctx context.Context, in *PrepareIncomingRequest, opts ...grpc.CallOption) (*PrepareIncomingResponse, error)
	// SendSandboxState streams the source's serialized SandboxState
	// to the destination in chunks. The destination applies the
	// state before the cutover so post-cutover read paths return
	// sane data immediately. Payload bytes do NOT include the QEMU
	// memory pages — those flow directly between the two QEMU
	// processes via the QMP migrate channel.
	SendSandboxState(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SandboxStateChunk, SendSandboxStateResponse], error)
	// CompleteHandoff is called by the source shim once QMP reports
	// phase=completed. The destination verifies its side and flips
	// its sandbox mode from Incoming to Owner. Returning success
	// from this RPC is the destination's commitment that it now
	// owns the sandbox.
	CompleteHandoff(ctx context.Context, in *CompleteHandoffRequest, opts ...grpc.CallOption) (*CompleteHandoffResponse, error)
	// AbortHandoff is called by either side to tear down an
	// in-flight migration. The destination tears down its QEMU and
	// unbinds the unix socket; the source separately calls
	// hypervisor.CancelMigration() against its own QEMU.
	AbortHandoff(ctx context.Context, in *AbortHandoffRequest, opts ...grpc.CallOption) (*AbortHandoffResponse, error)
}

type migrationCoordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewMigrationCoordinatorClient(cc grpc.ClientConnInterface) MigrationCoordinatorClient {
	return &migrationCoordinatorClient{cc}
}

func (c *migrationCoordinatorClient) PrepareIncoming(ctx context.Context, in *PrepareIncomingRequest, opts ...grpc.CallOption) (*PrepareIncomingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareIncomingResponse)
	err := c.cc.Invoke(ctx, MigrationCoordinator_PrepareIncoming_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationCoordinatorClient) SendSandboxState(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SandboxStateChunk, SendSandboxStateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MigrationCoordinator_ServiceDesc.Streams[0], MigrationCoordinator_SendSandboxState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SandboxStateChunk, SendSandboxStateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MigrationCoordinator_SendSandboxStateClient = grpc.ClientStreamingClient[SandboxStateChunk, SendSandboxStateResponse]

func (c *migrationCoordinatorClient) CompleteHandoff(ctx context.Context, in *CompleteHandoffRequest, opts ...grpc.CallOption) (*CompleteHandoffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteHandoffResponse)
	err := c.cc.Invoke(ctx, MigrationCoordinator_CompleteHandoff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationCoordinatorClient) AbortHandoff(ctx context.Context, in *AbortHandoffRequest, opts ...grpc.CallOption) (*AbortHandoffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortHandoffResponse)
	err := c.cc.Invoke(ctx, MigrationCoordinator_AbortHandoff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MigrationCoordinatorServer is the server API for MigrationCoordinator service.
// All implementations must embed UnimplementedMigrationCoordinatorServer
// for forward compatibility.
type MigrationCoordinatorServer interface {
	// PrepareIncoming is called by the source shim once the
	// destination shim is up and its hypervisor is in -incoming
	// mode. The destination acks readiness with the URI that QEMU
	// is listening on, so the source can target its QMP migrate
	// command at the right address.
	PrepareIncoming(context.Context, *PrepareIncomingRequest) (*PrepareIncomingResponse, error)
	// SendSandboxState streams the source's serialized SandboxState
	// to the destination in chunks. The destination applies the
	// state before the cutover so post-cutover read paths return
	// sane data immediately. Payload bytes do NOT include the QEMU
	// memory pages — those flow directly between the two QEMU
	// processes via the QMP migrate channel.
	SendSandboxState(grpc.ClientStreamingServer[SandboxStateChunk, SendSandboxStateResponse]) error
	// CompleteHandoff is called by the source shim once QMP reports
	// phase=completed. The destination verifies its side and flips
	// its sandbox mode from Incoming to Owner. Returning success
	// from this RPC is the destination's commitment that it now
	// owns the sandbox.
	CompleteHandoff(context.Context, *CompleteHandoffRequest) (*CompleteHandoffResponse, error)
	// AbortHandoff is called by either side to tear down an
	// in-flight migration. The destination tears down its QEMU and
	// unbinds the unix socket; the source separately calls
	// hypervisor.CancelMigration() against its own QEMU.
	AbortHandoff(context.Context, *AbortHandoffRequest) (*AbortHandoffResponse, error)
	mustEmbedUnimplementedMigrationCoordinatorServer()
}

// UnimplementedMigrationCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMigrationCoordinatorServer struct{}

func (UnimplementedMigrationCoordinatorServer) PrepareIncoming(context.Context, *PrepareIncomingRequest) (*PrepareIncomingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareIncoming not implemented")
}
func (UnimplementedMigrationCoordinatorServer) SendSandboxState(grpc.ClientStreamingServer[SandboxStateChunk, SendSandboxStateResponse]) error {
	return status.Error(codes.Unimplemented, "method SendSandboxState not implemented")
}
func (UnimplementedMigrationCoordinatorServer) CompleteHandoff(context.Context, *CompleteHandoffRequest) (*CompleteHandoffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteHandoff not implemented")
}
func (UnimplementedMigrationCoordinatorServer) AbortHandoff(context.Context, *AbortHandoffRequest) (*AbortHandoffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortHandoff not implemented")
}
func (UnimplementedMigrationCoordinatorServer) mustEmbedUnimplementedMigrationCoordinatorServer() {}
func (UnimplementedMigrationCoordinatorServer) testEmbeddedByValue()                              {}

// UnsafeMigrationCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigrationCoordinatorServer will
// result in compilation errors.
type UnsafeMigrationCoordinatorServer interface {
	mustEmbedUnimplementedMigrationCoordinatorServer()
}

func RegisterMigrationCoordinatorServer(s grpc.ServiceRegistrar, srv MigrationCoordinatorServer) {
	// If the following call panics, it indicates UnimplementedMigrationCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MigrationCoordinator_ServiceDesc, srv)
}

func _MigrationCoordinator_PrepareIncoming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareIncomingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationCoordinatorServer).PrepareIncoming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationCoordinator_PrepareIncoming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationCoordinatorServer).PrepareIncoming(ctx, req.(*PrepareIncomingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationCoordinator_SendSandboxState_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MigrationCoordinatorServer).SendSandboxState(&grpc.GenericServerStream[SandboxStateChunk, SendSandboxStateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MigrationCoordinator_SendSandboxStateServer = grpc.ClientStreamingServer[SandboxStateChunk, SendSandboxStateResponse]

func _MigrationCoordinator_CompleteHandoff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteHandoffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationCoordinatorServer).CompleteHandoff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationCoordinator_CompleteHandoff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationCoordinatorServer).CompleteHandoff(ctx, req.(*CompleteHandoffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationCoordinator_AbortHandoff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortHandoffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationCoordinatorServer).AbortHandoff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationCoordinator_AbortHandoff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationCoordinatorServer).AbortHandoff(ctx, req.(*AbortHandoffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MigrationCoordinator_ServiceDesc is the grpc.ServiceDesc for MigrationCoordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MigrationCoordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "migration_coordinator.MigrationCoordinator",
	HandlerType: (*MigrationCoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareIncoming",
			Handler:    _MigrationCoordinator_PrepareIncoming_Handler,
		},
		{
			MethodName: "CompleteHandoff",
			Handler:    _MigrationCoordinator_CompleteHandoff_Handler,
		},
		{
			MethodName: "AbortHandoff",
			Handler:    _MigrationCoordinator_AbortHandoff_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendSandboxState",
			Handler:       _MigrationCoordinator_SendSandboxState_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "migration_coordinator.proto",
}
