//
// Copyright (c) 2026
//
// SPDX-License-Identifier: Apache-2.0
//

// Migration coordinator — shim-to-shim handoff protocol for Kata
// live migration. See
// docs/design/live-migration-shim-lifecycle.md for the conceptual
// contract and the handoff sequence diagram.
//
// This service is bound by the destination shim on a per-sandbox
// unix socket only when the experimental.live_migration feature is
// enabled. It is NOT exposed to containerd or any other client.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: migration_coordinator.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareIncomingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sandbox ID being migrated. Must match the ID the
	// destination shim was created with; mismatches are rejected.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Capabilities the source wants enabled for this migration.
	// Examples: "xbzrle", "compress", "postcopy-ram",
	// "auto-converge". The destination acks with a possibly
	// narrower set if it does not support a requested capability.
	RequestedCapabilities []string `protobuf:"bytes,2,rep,name=requested_capabilities,json=requestedCapabilities,proto3" json:"requested_capabilities,omitempty"`
	// Opaque snapshot of the source's hypervisor configuration.
	// The destination uses this to confirm the two sides are
	// compatible (e.g. same QEMU machine type, same CPU model).
	// Format is JSON for the initial implementation; may move to
	// protobuf in a future version.
	HypervisorConfigSummary []byte `protobuf:"bytes,3,opt,name=hypervisor_config_summary,json=hypervisorConfigSummary,proto3" json:"hypervisor_config_summary,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PrepareIncomingRequest) Reset() {
	*x = PrepareIncomingRequest{}
	mi := &file_migration_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareIncomingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareIncomingRequest) ProtoMessage() {}

func (x *PrepareIncomingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareIncomingRequest.ProtoReflect.Descriptor instead.
func (*PrepareIncomingRequest) Descriptor() ([]byte, []int) {
	return file_migration_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareIncomingRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *PrepareIncomingRequest) GetRequestedCapabilities() []string {
	if x != nil {
		return x.RequestedCapabilities
	}
	return nil
}

func (x *PrepareIncomingRequest) GetHypervisorConfigSummary() []byte {
	if x != nil {
		return x.HypervisorConfigSummary
	}
	return nil
}

type PrepareIncomingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URI the source's QMP migrate command should target.
	// For TCP migration, formatted as "tcp:host:port" (the same
	// string QMP itself accepts).
	IncomingUri string `protobuf:"bytes,1,opt,name=incoming_uri,json=incomingUri,proto3" json:"incoming_uri,omitempty"`
	// Subset of requested_capabilities that the destination
	// accepted. Source must enable only these on its end via
	// migrate-set-capabilities before issuing migrate.
	AcceptedCapabilities []string `protobuf:"bytes,2,rep,name=accepted_capabilities,json=acceptedCapabilities,proto3" json:"accepted_capabilities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PrepareIncomingResponse) Reset() {
	*x = PrepareIncomingResponse{}
	mi := &file_migration_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareIncomingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareIncomingResponse) ProtoMessage() {}

func (x *PrepareIncomingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareIncomingResponse.ProtoReflect.Descriptor instead.
func (*PrepareIncomingResponse) Descriptor() ([]byte, []int) {
	return file_migration_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareIncomingResponse) GetIncomingUri() string {
	if x != nil {
		return x.IncomingUri
	}
	return ""
}

func (x *PrepareIncomingResponse) GetAcceptedCapabilities() []string {
	if x != nil {
		return x.AcceptedCapabilities
	}
	return nil
}

type SandboxStateChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repeated on every chunk so the destination can validate
	// mid-stream that the source has not switched sandboxes on it.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Up to ~64 KiB of the serialized SandboxState. Chunks are
	// concatenated in send order; the destination must NOT
	// deserialize until the final chunk arrives.
	PayloadChunk []byte `protobuf:"bytes,2,opt,name=payload_chunk,json=payloadChunk,proto3" json:"payload_chunk,omitempty"`
	// True on the last chunk. The destination decodes the
	// accumulated payload only after seeing this flag.
	Final         bool `protobuf:"varint,3,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxStateChunk) Reset() {
	*x = SandboxStateChunk{}
	mi := &file_migration_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStateChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStateChunk) ProtoMessage() {}

func (x *SandboxStateChunk) ProtoReflect() protoreflect.Message {
	mi := &file_migration_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStateChunk.ProtoReflect.Descriptor instead.
func (*SandboxStateChunk) Descriptor() ([]byte, []int) {
	return file_migration_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *SandboxStateChunk) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxStateChunk) GetPayloadChunk() []byte {
	if x != nil {
		return x.PayloadChunk
	}
	return nil
}

func (x *SandboxStateChunk) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type SendSandboxStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total bytes the destination accumulated across all chunks.
	// Source compares with what it sent as a coarse integrity
	// check (the destination JSON-decode failure surfaces as a
	// gRPC error, not in this field).
	BytesReceived uint64 `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	// True if the destination successfully decoded the accumulated
	// payload as a valid SandboxState. False values are only
	// returned for in-progress streams; a fully-streamed-but-
	// undecodable payload returns a gRPC error instead.
	StateApplied  bool `protobuf:"varint,2,opt,name=state_applied,json=stateApplied,proto3" json:"state_applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSandboxStateResponse) Reset() {
	*x = SendSandboxStateResponse{}
	mi := &file_migration_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSandboxStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSandboxStateResponse) ProtoMessage() {}

func (x *SendSandboxStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSandboxStateResponse.ProtoReflect.Descriptor instead.
func (*SendSandboxStateResponse) Descriptor() ([]byte, []int) {
	return file_migration_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *SendSandboxStateResponse) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *SendSandboxStateResponse) GetStateApplied() bool {
	if x != nil {
		return x.StateApplied
	}
	return false
}

type CompleteHandoffRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox the source is handing off. Same ID across the whole
	// sequence; the destination rejects mismatches.
	SandboxId     string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteHandoffRequest) Reset() {
	*x = CompleteHandoffRequest{}
	mi := &file_migration_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteHandoffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteHandoffRequest) ProtoMessage() {}

func (x *CompleteHandoffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteHandoffRequest.ProtoReflect.Descriptor instead.
func (*CompleteHandoffRequest) Descriptor() ([]byte, []int) {
	return file_migration_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteHandoffRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type CompleteHandoffResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the destination transitioned from Incoming to Owner.
	// False would be a programmer error — the destination cannot
	// partially complete a handoff. Returned for completeness so a
	// caller can distinguish "did not transition" from a transport
	// error.
	Owner         bool `protobuf:"varint,1,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteHandoffResponse) Reset() {
	*x = CompleteHandoffResponse{}
	mi := &file_migration_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteHandoffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteHandoffResponse) ProtoMessage() {}

func (x *CompleteHandoffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteHandoffResponse.ProtoReflect.Descriptor instead.
func (*CompleteHandoffResponse) Descriptor() ([]byte, []int) {
	return file_migration_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteHandoffResponse) GetOwner() bool {
	if x != nil {
		return x.Owner
	}
	return false
}

type AbortHandoffRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Free-form reason for logs; not interpreted by the
	// destination. Examples: "source timeout", "user cancellation",
	// "destination unreachable".
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortHandoffRequest) Reset() {
	*x = AbortHandoffRequest{}
	mi := &file_migration_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortHandoffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortHandoffRequest) ProtoMessage() {}

func (x *AbortHandoffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortHandoffRequest.ProtoReflect.Descriptor instead.
func (*AbortHandoffRequest) Descriptor() ([]byte, []int) {
	return file_migration_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *AbortHandoffRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *AbortHandoffRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbortHandoffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortHandoffResponse) Reset() {
	*x = AbortHandoffResponse{}
	mi := &file_migration_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortHandoffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortHandoffResponse) ProtoMessage() {}

func (x *AbortHandoffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortHandoffResponse.ProtoReflect.Descriptor instead.
func (*AbortHandoffResponse) Descriptor() ([]byte, []int) {
	return file_migration_coordinator_proto_rawDescGZIP(), []int{7}
}

var File_migration_coordinator_proto protoreflect.FileDescriptor

const file_migration_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x1bmigration_coordinator.proto\x12\x15migration_coordinator\"\xaa\x01\n" +
	"\x16PrepareIncomingRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x125\n" +
	"\x16requested_capabilities\x18\x02 \x03(\tR\x15requestedCapabilities\x12:\n" +
	"\x19hypervisor_config_summary\x18\x03 \x01(\fR\x17hypervisorConfigSummary\"q\n" +
	"\x17PrepareIncomingResponse\x12!\n" +
	"\fincoming_uri\x18\x01 \x01(\tR\vincomingUri\x123\n" +
	"\x15accepted_capabilities\x18\x02 \x03(\tR\x14acceptedCapabilities\"m\n" +
	"\x11SandboxStateChunk\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12#\n" +
	"\rpayload_chunk\x18\x02 \x01(\fR\fpayloadChunk\x12\x14\n" +
	"\x05final\x18\x03 \x01(\bR\x05final\"f\n" +
	"\x18SendSandboxStateResponse\x12%\n" +
	"\x0ebytes_received\x18\x01 \x01(\x04R\rbytesReceived\x12#\n" +
	"\rstate_applied\x18\x02 \x01(\bR\fstateApplied\"7\n" +
	"\x16CompleteHandoffRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"/\n" +
	"\x17CompleteHandoffResponse\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\bR\x05owner\"L\n" +
	"\x13AbortHandoffRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x16\n" +
	"\x14AbortHandoffResponse2\xd4\x03\n" +
	"\x14MigrationCoordinator\x12p\n" +
	"\x0fPrepareIncoming\x12-.migration_coordinator.PrepareIncomingRequest\x1a..migration_coordinator.PrepareIncomingResponse\x12o\n" +
	"\x10SendSandboxState\x12(.migration_coordinator.SandboxStateChunk\x1a/.migration_coordinator.SendSandboxStateResponse(\x01\x12p\n" +
	"\x0fCompleteHandoff\x12-.migration_coordinator.CompleteHandoffRequest\x1a..migration_coordinator.CompleteHandoffResponse\x12g\n" +
	"\fAbortHandoff\x12*.migration_coordinator.AbortHandoffRequest\x1a+.migration_coordinator.AbortHandoffResponseB\x04Z\x02./b\x06proto3"

var (
	file_migration_coordinator_proto_rawDescOnce sync.Once
	file_migration_coordinator_proto_rawDescData []byte
)

func file_migration_coordinator_proto_rawDescGZIP() []byte {
	file_migration_coordinator_proto_rawDescOnce.Do(func() {
		file_migration_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migration_coordinator_proto_rawDesc), len(file_migration_coordinator_proto_rawDesc)))
	})
	return file_migration_coordinator_proto_rawDescData
}

var file_migration_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_migration_coordinator_proto_goTypes = []any{
	(*PrepareIncomingRequest)(nil),   // 0: migration_coordinator.PrepareIncomingRequest
	(*PrepareIncomingResponse)(nil),  // 1: migration_coordinator.PrepareIncomingResponse
	(*SandboxStateChunk)(nil),        // 2: migration_coordinator.SandboxStateChunk
	(*SendSandboxStateResponse)(nil), // 3: migration_coordinator.SendSandboxStateResponse
	(*CompleteHandoffRequest)(nil),   // 4: migration_coordinator.CompleteHandoffRequest
	(*CompleteHandoffResponse)(nil),  // 5: migration_coordinator.CompleteHandoffResponse
	(*AbortHandoffRequest)(nil),      // 6: migration_coordinator.AbortHandoffRequest
	(*AbortHandoffResponse)(nil),     // 7: migration_coordinator.AbortHandoffResponse
}
var file_migration_coordinator_proto_depIdxs = []int32{
	0, // 0: migration_coordinator.MigrationCoordinator.PrepareIncoming:input_type -> migration_coordinator.PrepareIncomingRequest
	2, // 1: migration_coordinator.MigrationCoordinator.SendSandboxState:input_type -> migration_coordinator.SandboxStateChunk
	4, // 2: migration_coordinator.MigrationCoordinator.CompleteHandoff:input_type -> migration_coordinator.CompleteHandoffRequest
	6, // 3: migration_coordinator.MigrationCoordinator.AbortHandoff:input_type -> migration_coordinator.AbortHandoffRequest
	1, // 4: migration_coordinator.MigrationCoordinator.PrepareIncoming:output_type -> migration_coordinator.PrepareIncomingResponse
	3, // 5: migration_coordinator.MigrationCoordinator.SendSandboxState:output_type -> migration_coordinator.SendSandboxStateResponse
	5, // 6: migration_coordinator.MigrationCoordinator.CompleteHandoff:output_type -> migration_coordinator.CompleteHandoffResponse
	7, // 7: migration_coordinator.MigrationCoordinator.AbortHandoff:output_type -> migration_coordinator.AbortHandoffResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_migration_coordinator_proto_init() }
func file_migration_coordinator_proto_init() {
	if File_migration_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migration_coordinator_proto_rawDesc), len(file_migration_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_migration_coordinator_proto_goTypes,
		DependencyIndexes: file_migration_coordinator_proto_depIdxs,
		MessageInfos:      file_migration_coordinator_proto_msgTypes,
	}.Build()
	File_migration_coordinator_proto = out.File
	file_migration_coordinator_proto_goTypes = nil
	file_migration_coordinator_proto_depIdxs = nil
}
